# Generated by Django 4.1.1 on 2022-11-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_payment_payment_info_payment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='partnerId',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='phoneUser',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
